iced-rs/iced_aw

examples/modal/src/main.rs
src/native/modal.rs

This PR adds `inner` and `inner_mut` methods to `modal::State` for geting a (mutable) reference to the inner state data of a modal and implements `Default` trait for `modal::State` if inner state implements `Default` too.

feat: add get inner state methods to modal state, impl default for modal state

---

Cargo.toml
examples/badge/Cargo.toml
examples/card/Cargo.toml
examples/color_picker/Cargo.toml
examples/date_picker/Cargo.toml
examples/floating_button/Cargo.toml
examples/modal/Cargo.toml
examples/tab_bar/Cargo.toml
examples/tabs/Cargo.toml
examples/tabs_min/Cargo.toml
examples/time_picker/Cargo.toml
examples/web/Cargo.toml

This PR updates the Iced dependency to the latest commit, wich should prevent a disaster.
A few week ago the dependency to `wgpu_glyp` was [updated](https://github.com/hecrj/iced/commit/5fc4210270852d8d633a63168d8a166a235236c6). At this time `wgpu_glyph` [replaced](https://github.com/hecrj/wgpu_glyph/commit/6d5a95ae0d434e851ee7fcbb088f891b9b292653) the `zerocopy` dependency with `bytemuck`.
Before that, `wgpu_glyp` had a dependency to ^0.3 zerocopy. 18 hours ago, zerocopy [published](https://crates.io/crates/zerocopy/versions) a new version 0.3.1 and had [mistakenly claimed const generics as stable](https://fuchsia.googlesource.com/fuchsia/+/df1162fe6146a1e95ba51b7649119e11ee8b10dc) - which are not. This has been noticed by the failed test at PR #4.

Update Iced to latest rev

---

src/native/modal.rs

Sorry for the small PR, but it seems I forgot about this while doing the other PR (i only really needed this now).
This adds a `is_shown` method to the `modal::State` to query if the modal will be shown or not.

feat(modal): state is_shown method

---

src/native/tabs.rs

The implementation of `Widget` for `Tabs` needs to overwrite the `overlay` method, otherwise picklist cannot be used inside of tabs.

Overwrite `overlay` method in Widget implementation for Tabs

---

README.md

- Iced uses 0.3, not a git commit
- Repo is now under the `iced-rs` org
- Cargo needs to be told the repo lives in `main`, else it will try `master` and fail
Will close #13

Fix README's cargo deps

---

Cargo.toml
examples/number_input/Cargo.toml
examples/number_input/src/main.rs
src/graphics/mod.rs
src/graphics/number_input.rs
src/lib.rs
src/native/mod.rs
src/native/number_input.rs
src/style/mod.rs
src/style/number_input.rs

Hi there. This is the implementation of ``NumberInput`` widget. Sorry for committing lately, I was very busy on my work recently. 
Feel free to give me some idea to improve this widget. Thanks you guys....

Add ``NumberInput`` widget

---

src/native/number_input.rs

The number-input renderer implementation for the Null renderer missed the `debug_assertion` configuration which resulted in failing release builds.
This PR fixes this.

Fix: add missing debug_assertions

---

src/web/grid.rs

This PR fixes a small compile error for the Grid widget on WASM targets.

Fix: Grid widget could not compiling on web

---

src/graphics/split.rs
src/native/split.rs

The Split widget was no hashing the layout of it's elements. In addition, the problems of the elements rendered outside the area could be solved.

Fix some small bugs and improve Split widget

---

src/graphics/split.rs
src/native/split.rs

This PR adds the `overlay` method implementation for the Split widget. In addition it adds a Default implementation and a method to get the current divider position to the Split's state. This should fix #31 .

Fix: overlay not shown in Split

---

README.md
src/lib.rs
src/web/mod.rs
src/web/tab_bar.rs
src/web/tab_bar/tab_label.rs
src/web/tabs.rs
src/web/tabs/tab_bar_position.rs

This PR adds the TabBar and Tabs widgets to the web as requested by #38 .
Known limitations:
- No icon support as there is currently no way of specifying the icon font on the web
- No hover styling as there is currently no easy way of styling on the web
@Icelk if something isn't working as expected, feel free to open up an issue. :slightly_smiling_face:

Implement TabBar and Tabs for web

---

src/native/split.rs

This PR adds the missing associated function for setting the style of the Split widget.

Add missing style configuration for Split

---

src/native/color_picker.rs
src/native/date_picker.rs
src/native/time_picker.rs

This is to fix the style functions in a few widgets. The error occurs as there is no longer a use for `<S>` so `<S>` is no longer preset by the compiler hence you must manually set it even though it does nothing now.

Removed no longer needed <S> from style functions

---

.gitignore
Cargo.toml
src/native/selection_list.rs
src/native/selection_list/list.rs
src/style/selection_list.rs

This PR implements an easy way to tell which item in a `SelectionList` is currently selected by tracking the index of the currently selected item and styling it accordingly.
Previously, `Style.selected_text_color` and `Style.selected_background` defined the styling of the item that the mouse was hovering over. These have been renamed to `Style.hovered_text_color` and `Style.hovered_background`, respectively, and `Style.selected_text_color` and `Style.selected_background` now accurately refer to the styling applied to the currently **selected** item.
I have verified that the `selection_list` example still works - no code changes were required.

Show which item is selected in `SelectionList`

---

.github/workflows/rustdoc.yml

This crate is not available on crates.io, so you can not read its docs on docs.rs.
I have a similar crate that can not be published to crates.io, so I just use GitHub pages for hosting the docs and linking to it from the readme:
https://github.com/Luro02/array-map/tree/gh-pages
and this is the link to the docs: https://luro02.github.io/array-map/
I think this would be nice to have for this crate, so I created this PR.
---
I don't know if you want to use a real domain name, which you can do by going to the settings of the repository under GitHub pages there is a field to add a custom domain and then adding this to the yaml:
```diff,yml
publish_branch: gh-pages
publish_dir: ./target/doc
+         cname: iced_aw.iced.rs
```
Otherwise, one could access the docs through this url: …

Build rustdoc to github pages

---

examples/floating_element/src/main.rs

by apply the custom button style with 200.0 radius, the button now looks like a round and similar to the example gif
the gif round is 
and the round created by PR

feat: make the floating button round

---

src/native/tabs.rs

Fixes #68 by implementing `Widget::operate` for `Tabs`.

Fix operations in Tabs

---

Cargo.toml
src/native/badge.rs
src/native/card.rs
src/native/color_picker.rs
src/native/date_picker.rs
src/native/floating_element.rs
src/native/grid.rs
src/native/modal.rs
src/native/number_input.rs
src/native/overlay/color_picker.rs
src/native/overlay/date_picker.rs
src/native/overlay/modal.rs
src/native/overlay/time_picker.rs
src/native/selection_list.rs
src/native/selection_list/list.rs
src/native/split.rs
src/native/tab_bar.rs
src/native/tabs.rs
src/native/time_picker.rs
src/native/wrap.rs

Note I have not tested this extensively, only branched, updated and ensured it compiles against my own project at https://github.com/mimblewimble/grin-gui
* Update version for iced, iced_native and iced_graphics
* Deal with addition of `BorderRadius`
* Deal with change to  `overlay` trait function of `Widget`

Compile against iced_rs 0.6.0

---

Cargo.toml
src/native/number_input.rs
src/native/tabs.rs

Only minor changes are needed to compile against `iced` 0.7.
I have tested all the programs in examples/ and they all compile, run and seem to work.
Updated `iced_native` to 0.8, `iced_graphics` to 0.6, `iced_style` to 0.6, `iced` to 0.7.
Examples `time_picker` and `date_picker` give deprecation warnings for `chrono`, but that is unrelated to the changes made.
There's some `cargo fmt` changes that should probably be done too, but I only applied formatting to code I changed in this PR.

Upgrade to iced 0.7

---

src/native/badge.rs
src/native/card.rs
src/native/floating_element.rs
src/native/grid.rs
src/native/modal.rs
src/native/number_input.rs
src/native/split.rs
src/native/tab_bar.rs
src/native/tabs.rs

Doctests seems to have been broken for at least a few commits. I noticed it before I started the 0.7 PR but decided not to change it in the 0.7 PR, as it did not bring any new errors.
The problem is that `Theme` has been added, and I couldn't figure out how to make `Null` take a theme easily. It was a much smaller change to simply use the native type in the doctests for the native elements. It shouldn't matter which type we import as the imports are hidden in the documentation anyway and are just used to make the doctests run successfully. It also makes a ton of sense to use the native type in the native files.
With this PR, `cargo test` will be successful again.
I also ran `cargo fmt` on the files I changed. But there are still other files which have not been changed in this PR which …

Fix doctests by using the native type version

---

examples/floating_element/src/main.rs
examples/grid/src/main.rs
examples/number_input/src/main.rs
examples/tab_bar/src/main.rs
examples/tabs/src/main.rs
src/native/cupertino/cupertino_spinner.rs
src/native/helpers.rs
src/native/tab_bar.rs
src/native/tabs.rs

This PR formats the code fixing the CI

Format the code

---

.github/workflows/clippy.yml
.github/workflows/format.yml

add nightly to the test for fmt.

Update format.yml and clippy.yml

---

.vscode/launch.json
Cargo.toml
examples/context_menu/Cargo.toml
examples/context_menu/src/main.rs
examples/floating_element/src/main.rs
examples/grid/src/main.rs
examples/number_input/src/main.rs
examples/tab_bar/src/main.rs
examples/tabs/src/main.rs
src/lib.rs
src/native/context_menu.rs
src/native/cupertino/cupertino_spinner.rs
src/native/helpers.rs
src/native/mod.rs
src/native/overlay/context_menu.rs
src/native/overlay/mod.rs
src/native/tab_bar.rs
src/native/tabs.rs
src/style/context_menu.rs
src/style/mod.rs

This pull request implement #133.
I think this widget could be improved in the future by adapting menu to be used as overlay (only one tree of course not the entire bar).
The overlay appears at the place where the right click was made but apart from that, the implementation is quit naive and does not take into account the available space. But the menu have already this behaviour.

Impl ContextMenu

---

src/native/floating_element.rs
src/native/overlay/floating_element.rs

Removing this seemingly unnecessary `Clone` attribute allows for `Message`s holding one usage not `Clone` attributes.
Such as a unique handle to a connection for example, or a `channel::Sender`.

Remove unnecessary `Clone` requirement on FloatingElement's `Message`

---

src/native/split.rs

As far as I can see this bound is not needed anywhere and removing it should not break anything

split: Remove unneeded Message: Clone bound

---

.github/workflows/clippy.yml
.github/workflows/format.yml

`clippy` and `rustfmt` checks for `nightly` are really unstable, so better to use only the `stable` version

Remove nightly version for clippy and format checks 

---

.github/workflows/clippy.yml

This PR transforms `clippy` warnings into errors. This choice allows to have a better maintainability of the code.

Transform clippy warnings into errors

---

CHANGELOG.md
src/core/mod.rs
src/core/time.rs
src/native/badge.rs
src/native/card.rs
src/native/color_picker.rs
src/native/date_picker.rs
src/native/floating_element.rs
src/native/floating_element/anchor.rs
src/native/floating_element/offset.rs
src/native/helpers.rs
src/native/icon_text.rs
src/native/modal.rs
src/native/number_input.rs
src/native/overlay/date_picker.rs
src/native/tabs.rs
src/native/time_picker.rs
src/native/wrap.rs
src/style/colors.rs
src/style/context_menu.rs
src/style/menu_bar.rs
src/style/modal.rs

Fixed an outdated Modal example, then noticed that a lot of the other docs were not building correctly on docs.rs.
Ended up doing a full sweep on the docs.

Doc Cleanup

---

examples/menu/src/main.rs
src/native/menu/menu_inner.rs

Add `ItemHeight::Dynamic` #158 
Automatically chooses proper item height in these cases:
- Fixed height
- Shrink height
- Menu tree height
When none of these is the case it will fallback to the default value

Menu dynamic item height

---

examples/menu/src/main.rs
src/native/menu/menu_bar.rs
src/native/menu/menu_inner.rs

Fix #150 by adding `main_offset` and `cross_offset`
`main_offset` moves all the menus in the vertical open direction
`cross_offset` moves each menu in the horizontal open direction
Before
<br/>
After (main_offset = 13,  cross_offset = 16)

Submenu offset

---

src/native/tab_bar.rs

This pr adds a method and a enum on where to render the `Icon` in `Icontext` enum, in any of the four directions.

new positions to tab_bar!!!

---

src/native/card.rs

Currently cards can't have overlays, which this PR implements, however a few questions remain:
- All the children have their own wrapper layout, I'm sure there's a reason for it. This means the overlay method must be called for the first child within the wrapper (the actual child layout), otherwise only the first one will be rendered (eg. Row [ PickList (this only), PickList, PickList ]). This requires either an unwrap or some kind of logic, which is, even if it's just a line, may not be necessary. Could this be a valid reason to remove the wrappers and use the child layouts direcly?
- is there a point to have overlays for the header or the footer? In my opinion only allowing the body to have overlays could be sensible, however I do have some use cases from the past where I had to use …

Card overlays

---

src/native/overlay/context_menu.rs

fix for https://github.com/iced-rs/iced_aw/issues/185

ContextMenu respects window borders and resizing

---

src/native/overlay/context_menu.rs

This tries to fix https://github.com/iced-rs/iced_aw/issues/178 .
This changes when events are forwarded to the child of the context menu. 
It allows widgets like sliders to be used in a context menu since it now forwards "Released" events to the child. (_Otherwise the slider would still be grabbed when reopening the menu_)
This also prevents a click event from going _through_ the context menu, when e.g. a "Released" event happens inside the content bounds but the content returns `Ignored`. Since the context_menu takes action here by closing itself it also should catch the event.

Update event handling for context_menu overlay

---

src/native/menu/menu_bar.rs

If MenuBar replaces a different (stateless) widget in the view for an application it causes a downcast error because the state is never initialised correctly: since tag() is not implemented for it, diff() gets called instead of state()/children().

Set tag for MenuBar

---

examples/wrap/src/main.rs
src/native/number_input.rs

The `wrap` example looks like this to me:
Changing the controls column width from the default `iced::Length::Shrink` to either `iced::Length::Fixed(value)` or `iced::Length::FillPortion(value)` fixes the example program.

Wrap example is broken

---

src/native/grid/layout.rs

This fixes the grid padding bug that I overlooked in the previous PR.
I'm still looking into the issue where other widgets can overlap the grid widget when the available space is too small to render them next to each other.

Fix grid padding

---

src/style/tab_bar.rs

im not sure if this was intentional, but hovering over an active tab will not highlight it anymore, which i find a bit odd
looks like this behavior was introduced in #206
this pull just changes it to always use the strong highlight color, similar to how was before

change TabBar hovered appearance for default style

---

src/core/date.rs
src/native/date_picker.rs
src/native/overlay/date_picker.rs

Adds the ability to set font size on the date picker overlay as discussed in #208.
Also dynamically changes the size of the overlay to best fit the relevant font size.

Add font size to date picker

---

Cargo.lock
Cargo.toml
examples/WidgetIDReturn/Cargo.toml
examples/badge/Cargo.toml
examples/card/Cargo.toml
examples/color_picker/Cargo.toml
examples/context_menu/Cargo.toml
examples/cupertino/cupertino_spinner/Cargo.toml
examples/drop_down/Cargo.toml
examples/floating_element multioverlay/Cargo.toml
examples/floating_element_anchors/Cargo.toml
examples/font_loading/Cargo.toml
examples/grid/Cargo.toml
examples/menu/Cargo.toml
examples/modal/Cargo.toml
examples/modal_component/Cargo.toml
examples/multiple_modals/Cargo.toml
examples/number_input/Cargo.toml
examples/selection_list/Cargo.toml
examples/sliderbar/Cargo.toml
examples/spinner/Cargo.toml
examples/split/Cargo.toml
examples/split_scroller/Cargo.toml
examples/tab_bar/Cargo.toml
examples/tabs/Cargo.toml
examples/wrap/Cargo.toml

They are automatically activated for users of this crate.
My specific use-case:
For some reason, starting with iced-0.12 activating the wgpu-feature results in a "unwrap on a None-value" panic when executing on a rasperry pi.
Additionally, I don't want to activate the "tokio"-feature, since I don't use it for anything else (yet), and tokio isn't exactly small.
All examples are still compiling (added missing "icons"-feature where rustc was complaining).
However, I noticed some weirdness (not addressed here, to keep the scope small):
- wgpu requirement in examples:
- panic on tab_bar (start) and multiple_modals (after button press)
- sometimes starts with black window
- color-picker bottom line stays empty
- menu: when focusing an item, every other item is only a black box
- …

only activate required iced-features

---

src/widgets/helpers.rs

Fixes
```
error[E0277]: the trait bound `Theme: iced::advanced::Renderer` is not satisfied
--> src/main.rs:34:40
|
34  |         let content: Element<_> = grid(rows)
|                                   ---- ^^^^ the trait `iced::advanced::Renderer` is not implemented for `Theme`
|                                   |
|                                   required by a bound introduced by this call
|
= help: the following other types implement trait `iced::advanced::Renderer`:
iced::Renderer
iced::advanced::iced_graphics::Renderer<B>
iced::advanced::renderer::Null
note: required by a bound in `grid`
--> /home/exidex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_aw-0.8.0/src/native/helpers.rs:268:15
|
264 | pub fn grid<Message, Renderer>(
|        ---- required by a bound in this …
```

Fix broken grid generic parameters

---

examples/floating_element/src/main.rs

this PR can fix the example button doesn't highlight when it is hovered

fix: button doesn't highlight when it is hovered

---

examples/tab_bar/src/main.rs

Found during an investigation in the same area, the current tab was not highlighted correctly.

add missing set_active_tab

---

src/widgets/number_input.rs

Fixes #235.
This code change makes sure to not do any operations that might overflow or underflow.
The code makes the assumption that it does not receive the widget in a broken state, ie the invariant
```rust
self.bounds.0 <= self.value <= self.bounds.1
```
must be true for the code to be correct. If it is, then the result after the operation will uphold the same invariant.
Such a topic is very error prone, so please feel free to try and find problems in the code I wrote.

Fix number input over/underflow

---

src/widgets/badge.rs
src/widgets/card.rs
src/widgets/cupertino/cupertino_spinner.rs
src/widgets/number_input.rs
src/widgets/segmented_button.rs
src/widgets/selection_list.rs
src/widgets/spinner.rs
src/widgets/split.rs
src/widgets/tab_bar.rs
src/widgets/tabs.rs

Widgets in iced allow to change their height and their width with an API like this :
```rust
pub fn width(mut self, width: impl Into<Length>) -> Self
```
This is especially useful when setting a fixed width/height:
```rust
my_widget.width(30);
```
instead of 
```rust
my_widget.width(Length::Fixed(30.));
```
This PR proposes to change the API to make it more in line with the one in iced.

Replace Length with impl Into<Length> in width/height APIs

---

src/widgets/number_input.rs

https://github.com/iced-rs/iced_aw/issues/223
Simply allows disabling mouse scroll events for the `NumberInput`. Not sure how needed this is, but I can see it being annoying where the outer scrollable is small, as the user could accidentally modify the value.
The issue also mentions the idea of the event being opt-in, instead of opt-out which can be changed in `NumberInput::new` if preferred. Though personally I don't think its worth changing default behavior.

Allow disabling scroll events for NumberInput.

---

src/widgets/tabs.rs

I have an app where I create the list of tabs at runtime through the use of an iterator. The allocation of a Vec which is then immediately iterated upon seemed a bit wasteful. If there was a reason for the particular API, please do tell. If not, here is a simple change which changes the function to accept any IntoIterator, which would then avoid this allocation in my case. Further, the existing interface should be preserved, as Vec implements IntoIterator, in addition to that the size_hit will return the length of the Vec.
Thank you for a great couple of widgets in this library!

Use IntoIterator instead of Vec for tabs

---

src/widgets/menu/menu_bar.rs

In our [pigg](https://github.com/andrewdavidmackenzie/pigg) app, we encountered a scenario where it was necessary to close the menu bar when the user clicks on the menu bar itself.
To address this need, I implemented the feature to close the menu bar when clicked. When the menu bar is clicked, it toggles its open/close state.
Any feedback is appreciated!

Toggle Menu Bar on Click

---

Cargo.lock
src/style/menu_bar.rs
src/widgets/menu/menu_tree.rs
src/widgets/overlay/color_picker.rs
src/widgets/overlay/date_picker.rs
src/widgets/overlay/time_picker.rs
src/widgets/quad.rs
src/widgets/slide_bar.rs
src/widgets/tab_bar.rs

I had a few compile errors, I assume because I pulled a newer version of Iced. So here's a commit that fixes those build errors.

use new alignment methods from iced

---

Cargo.lock
Cargo.toml
examples/typed_input/Cargo.toml
examples/typed_input/src/main.rs
src/widgets.rs
src/widgets/number_input.rs
src/widgets/typed_input.rs

Should fix #234 
To fix it, I created a new widget, the TypedInput, it allows the user to write anything in a TextInput, but only send messages when it is a correct value, and then the message contain this value (not the string).
I then modify NumberInput to use this widget instead of a standard TextInput.
My code may not be the cleanest or respect all the guideline of the repo, so I'll be happy to edit it according to your liking.

Adding support for dots in number_input

---

examples/typed_input/src/main.rs
src/lib.rs
src/widgets.rs
src/widgets/helpers.rs
src/widgets/number_input.rs
src/widgets/sidebar/column.rs
src/widgets/sidebar/row.rs
src/widgets/typed_input.rs

I added the helpers I didn't include in my precedent PR (#267).
At the same time I added a placeholder for TypedInput, given the content can be empty

Adding  helpers and placeholder for typed_input

---

examples/typed_input/src/main.rs
src/widgets/helpers.rs
src/widgets/number_input.rs
src/widgets/typed_input.rs

I modified the method on the TypedInput to match the ones on TextInput
And change the on_submit message to send a result, either Ok(value) or an error with the current text when it's not valid

Changing the TypedInput APi to a one similar to the TextInput's

---

src/widgets/menu/menu_tree.rs

When a menu had at most one item, it was falling with an index out of bound exception.
An empty menu would return :
```sh
thread 'main' panicked at /home/user/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/18cf814/src/widgets/menu/menu_tree.rs:245:25:
index out of bounds: the len is 0 but the index is 0
```
And a menu with one item :
```sh
thread 'main' panicked at /home/user/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/18cf814/src/widgets/menu/menu_tree.rs:454:19:
range end index 2 out of range for slice of length 1
```
It seems to come from missing parenthesis during the comparison.
This PR is supposed to solve that

Correcting menu (index error when less than 2 items)

---

src/widget/number_input.rs

this prevents the max width of the number_input widget from being reduced by the padding
in this example we have a row with 3 collumns filled with buttons _(set to fill)_ and the number_input _(with 22 padding)_ in the middle.
left is before, right with this change
_the call to shrink may have been used here to apply padding to the content, but the padding is already set on the content itself so this is not needed_

fix max width being reduced by padding in number_input

---

Cargo.lock
Cargo.toml
examples/menu.rs

Resolves #289. Maybe creating a new release on crates.io would be worth considering?

bump iced to v0.13.0

---

src/widget/number_input.rs

This enables users to set the ID of the underlying `TextInput`.
Fixes iced-rs/iced_aw#295.

Added the `id()` method to `NumberInput`

---

src/style/selection_list.rs

Previously `selection_list` had hardcoded colors which were more geared towards light themes and didn't adjust them according to the theme you set for iced, this PR makes it so `selection_list` uses palette of the set iced theme.

Make `selection_list` follow iced theme

---

examples/side_bar/main.rs
src/widget/number_input.rs
src/widget/spinner.rs

I did the changes to only `spinner.rs`. But `cargo fmt` changed the other files.

Fixing the compilation error caused by std Instant on WASM targets

---

src/widget/number_input.rs

Mac keyboards are using the ‘delete’ button as the backspace for text inputs. So the unicode character is `\u{7f}`. But in other platforms, it is `\u{8}`. `iced_core::keyboard` module is already handling it. So we can re-use that functionality for backspace.

Fixing the backspace issue in number inputs on Mac

---

.pre-commit-config.yaml
CHANGELOG.md
Cargo.toml
README.md
examples/number_input.rs
examples/typed_input.rs
examples/widget_id_return/main.rs
examples/widget_id_return/numberinput.rs
examples/wrap.rs
src/widget/helpers.rs
src/widget/number_input.rs
src/widget/typed_input.rs

I rewrote the logic of `NumberInput` to solve issues #308, #304, #299 and the problem with included and excluded bounds.
The `NumberInput` unlike the `TypedInput` never allows invalid entries.
People who try to implement a floating-point number should follow the way the `f32` is done; it can end with a `.`
I also added the support for any characters in the number, it just has to always be a valid number, regarding the `T::from_str` function.
I merge `content_width` and `width`. It seems to fix issues #286 and #278

Correcting several issues with `NumberInput`

---

src/widget/number_input.rs
src/widget/typed_input.rs

I add all the relevant methods of TextInput in NumberInput and TypedInput
I did not add the secure method for NumberInput as I thought it was not relevant

Updating the methods of NumberInput and TypedInput

---

src/widget/menu/menu_bar_overlay.rs

When menu/sub-menu changes due to clicking on a menu item, sometimes an index out of range error occurs at line 108, and this avoids it at least.

Avoid index out of range panic

---

src/widget/grid/types.rs

I was in a situation I was returning a `GridRow` with a different `Message` type so I needed to map them to the type I needed. Since `GridRow` is basically a `Vec<Element>`, I just iterate the elements and call `Element::map` function.

Add map support to GridRow

---

src/widget/grid/layout.rs

This PR changed the `Grid` element's layout behavior.
- Previously, the `Grid` would impose the width requirement of each column to the left onto the next columns.
- This PR allows columns to have a width less than a column to their left.
I believe this was not intentional and is a bug.

Fix `Grid` columns inheriting columns' widths to their left

---

.cargo/config.toml
Cargo.lock
Cargo.toml

This is my first contribution here on github so please bear with me.
Compiling the iced_aw project and its examples for `wasm32-unknown-unknown` will result in this error: 
```
❯ cargo build --target wasm32-unknown-unknown
Compiling getrandom v0.3.1
error: The wasm32-unknown-unknown targets are not supported by default; you may need to enable the "wasm_js" configuration flag. Note that enabling the `wasm_js` feature flag alone is insufficient. For more information see: https://docs.rs/getrandom/#webassembly-support
--> /Users/miivers/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/getrandom-0.3.1/src/backends.rs:159:9
|
159 | /         compile_error!(
160 | |             "The wasm32-unknown-unknown targets are not supported by default; \
161 | |             you may need to enable the …
```

Fix WASM build

---

src/widget/grid/types.rs

In this PR I added the `extend` method for Grid and GridRow in the same way to what's already available for [Row](https://docs.iced.rs/iced/widget/struct.Row.html#method.extend) and [Column](https://docs.iced.rs/iced/widget/struct.Column.html#method.extend) in standard Iced widgets.
This allows to add children to the widget in a concise way.

Add extend for Grid and GridRow

---

src/widget/selection_list/list.rs

For a selection list, currently the hovered item highlight persists even when the cursor moves out of bounds, reproducible in the `selection_list` example.
This is solved by resetting the `hovered_option` state when the cursor is out of bounds.
Before:
After:

End selection_list hover highlight when cursor is outside bounds

---

examples/number_input.rs
src/widget/number_input.rs

Fixes #261. Fixes #333. 
* Allow lone minus sign in input, mapping it to 0 - the same way as for empty input.
* Fix too eager handling of numpad keys - numpad keys are misdetected by core framework (see https://github.com/iced-rs/iced/pull/2278), this PR aligns their behaviour with `TextInput`.

Fix negative inputs and numpad handling by NumberInput
